DEBUG 2025-07-01 07:16:05.923 UTC: 	 CRAB Client version: v3.250522
DEBUG 2025-07-01 07:16:05.923 UTC: 	 Running on: Linux cms-fe01.rcac.purdue.edu 4.18.0-513.18.1.el8_9.x86_64 #1 SMP Wed Feb 21 21:34:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-07-01 07:16:05.923 UTC: 	 Not using Singularity
DEBUG 2025-07-01 07:16:05.923 UTC: 	 Operating System: Rocky Linux 8.9 (Green Obsidian)
DEBUG 2025-07-01 07:16:05.923 UTC: 	 Executing command: 'submit'
DEBUG 2025-07-01 07:16:05.923 UTC: 	 Found CRAB cache file /home/awesole/.crab3
INFO 2025-07-01 07:16:05.924 UTC: 	 Will use CRAB configuration file D0_data_submit.py
DEBUG 2025-07-01 07:16:05.924 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-07-01 07:16:05.926 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-07-01 07:16:05.926 UTC: 	 Working area '/home/awesole/VertexCP_2/CMSSW_13_2_11/src/VertexCompositeAnalysis/VertexCompositeProducer/test/crab/Run3_D0_Data_miniAOD/crab_Run3_D0_Data_miniAOD' already exists 
Please change the requestName in the config file
ERROR 2025-07-01 07:16:05.926 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/home/awesole/VertexCP_2/CMSSW_13_2_11/src/VertexCompositeAnalysis/VertexCompositeProducer/test/crab/Run3_D0_Data_miniAOD/crab_Run3_D0_Data_miniAOD' already exists 
Please change the requestName in the config file
INFO 2025-07-01 07:16:05.929 UTC: 	 Log file is /home/awesole/VertexCP_2/CMSSW_13_2_11/src/VertexCompositeAnalysis/VertexCompositeProducer/test/crab/crab.log
DEBUG 2025-07-10 20:44:08.659 UTC: 	 CRAB Client version: v3.250522
DEBUG 2025-07-10 20:44:08.659 UTC: 	 Running on: Linux cms-fe00.rcac.purdue.edu 4.18.0-513.18.1.el8_9.x86_64 #1 SMP Wed Feb 21 21:34:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-07-10 20:44:08.659 UTC: 	 Not using Singularity
DEBUG 2025-07-10 20:44:08.660 UTC: 	 Operating System: Rocky Linux 8.9 (Green Obsidian)
DEBUG 2025-07-10 20:44:08.660 UTC: 	 Executing command: 'submit'
DEBUG 2025-07-10 20:44:08.660 UTC: 	 Found CRAB cache file /home/awesole/.crab3
INFO 2025-07-10 20:44:08.662 UTC: 	 Will use CRAB configuration file D0_data_submit.py
DEBUG 2025-07-10 20:44:08.662 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-07-10 20:44:08.664 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-07-10 20:44:08.665 UTC: 	 Working area '/home/awesole/VertexCP_2/CMSSW_13_2_11/src/VertexCompositeAnalysis/VertexCompositeProducer/test/crab/test_1_file/crab_test_1_file' already exists 
Please change the requestName in the config file
ERROR 2025-07-10 20:44:08.665 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/home/awesole/VertexCP_2/CMSSW_13_2_11/src/VertexCompositeAnalysis/VertexCompositeProducer/test/crab/test_1_file/crab_test_1_file' already exists 
Please change the requestName in the config file
INFO 2025-07-10 20:44:08.669 UTC: 	 Log file is /home/awesole/VertexCP_2/CMSSW_13_2_11/src/VertexCompositeAnalysis/VertexCompositeProducer/test/crab/crab.log
DEBUG 2025-07-11 04:19:46.950 UTC: 	 CRAB Client version: v3.250522
DEBUG 2025-07-11 04:19:46.950 UTC: 	 Running on: Linux cms-fe00.rcac.purdue.edu 4.18.0-513.18.1.el8_9.x86_64 #1 SMP Wed Feb 21 21:34:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-07-11 04:19:46.950 UTC: 	 Not using Singularity
DEBUG 2025-07-11 04:19:46.951 UTC: 	 Operating System: Rocky Linux 8.9 (Green Obsidian)
DEBUG 2025-07-11 04:19:46.951 UTC: 	 Executing command: 'getsandbox'
DEBUG 2025-07-11 04:19:46.951 UTC: 	 Found CRAB cache file /home/awesole/.crab3
DEBUG 2025-07-11 05:21:20.830 UTC: 	 CRAB Client version: v3.250522
DEBUG 2025-07-11 05:21:20.830 UTC: 	 Running on: Linux cms-fe01.rcac.purdue.edu 4.18.0-513.18.1.el8_9.x86_64 #1 SMP Wed Feb 21 21:34:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-07-11 05:21:20.830 UTC: 	 Not using Singularity
DEBUG 2025-07-11 05:21:20.830 UTC: 	 Operating System: Rocky Linux 8.9 (Green Obsidian)
DEBUG 2025-07-11 05:21:20.830 UTC: 	 Executing command: 'status'
DEBUG 2025-07-11 05:21:20.831 UTC: 	 Found CRAB cache file /home/awesole/.crab3
ERROR 2025-07-11 05:21:20.832 UTC: 	 Error: crab/test_1_file/crab_test_1_file/ is not a valid CRAB project directory.
ERROR 2025-07-11 05:21:20.832 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/status.py", line 49, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 691, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab/test_1_file/crab_test_1_file/ is not a valid CRAB project directory.
INFO 2025-07-11 05:21:20.834 UTC: 	 Log file is /home/awesole/VertexCP_2/CMSSW_13_2_11/src/VertexCompositeAnalysis/VertexCompositeProducer/test/crab/crab.log
DEBUG 2025-07-11 18:45:25.651 UTC: 	 CRAB Client version: v3.250522
DEBUG 2025-07-11 18:45:25.651 UTC: 	 Running on: Linux cms-fe00.rcac.purdue.edu 4.18.0-513.18.1.el8_9.x86_64 #1 SMP Wed Feb 21 21:34:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-07-11 18:45:25.651 UTC: 	 Not using Singularity
DEBUG 2025-07-11 18:45:25.651 UTC: 	 Operating System: Rocky Linux 8.9 (Green Obsidian)
DEBUG 2025-07-11 18:45:25.651 UTC: 	 Executing command: 'submit'
DEBUG 2025-07-11 18:45:25.651 UTC: 	 Found CRAB cache file /home/awesole/.crab3
INFO 2025-07-11 18:45:25.653 UTC: 	 Will use CRAB configuration file D0_data_submit.py
DEBUG 2025-07-11 18:45:25.653 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-07-11 18:45:25.876 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-07-11 18:45:25.877 UTC: 	 Working area '/home/awesole/VertexCP_2/CMSSW_13_2_11/src/VertexCompositeAnalysis/VertexCompositeProducer/test/crab/test_1_file/crab_test_1_file' already exists 
Please change the requestName in the config file
ERROR 2025-07-11 18:45:25.877 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/home/awesole/VertexCP_2/CMSSW_13_2_11/src/VertexCompositeAnalysis/VertexCompositeProducer/test/crab/test_1_file/crab_test_1_file' already exists 
Please change the requestName in the config file
INFO 2025-07-11 18:45:25.881 UTC: 	 Log file is /home/awesole/VertexCP_2/CMSSW_13_2_11/src/VertexCompositeAnalysis/VertexCompositeProducer/test/crab/crab.log
DEBUG 2025-07-11 18:49:19.688 UTC: 	 CRAB Client version: v3.250522
DEBUG 2025-07-11 18:49:19.688 UTC: 	 Running on: Linux cms-fe00.rcac.purdue.edu 4.18.0-513.18.1.el8_9.x86_64 #1 SMP Wed Feb 21 21:34:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-07-11 18:49:19.688 UTC: 	 Not using Singularity
DEBUG 2025-07-11 18:49:19.688 UTC: 	 Operating System: Rocky Linux 8.9 (Green Obsidian)
DEBUG 2025-07-11 18:49:19.688 UTC: 	 Executing command: 'submit'
DEBUG 2025-07-11 18:49:19.689 UTC: 	 Found CRAB cache file /home/awesole/.crab3
INFO 2025-07-11 18:49:19.691 UTC: 	 Will use CRAB configuration file D0_data_submit.py
DEBUG 2025-07-11 18:49:19.692 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-07-11 18:49:19.781 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-07-11 18:49:19.781 UTC: 	 Working area '/home/awesole/VertexCP_2/CMSSW_13_2_11/src/VertexCompositeAnalysis/VertexCompositeProducer/test/crab/test_1_file/crab_test_1_file' already exists 
Please change the requestName in the config file
ERROR 2025-07-11 18:49:19.782 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/home/awesole/VertexCP_2/CMSSW_13_2_11/src/VertexCompositeAnalysis/VertexCompositeProducer/test/crab/test_1_file/crab_test_1_file' already exists 
Please change the requestName in the config file
INFO 2025-07-11 18:49:19.786 UTC: 	 Log file is /home/awesole/VertexCP_2/CMSSW_13_2_11/src/VertexCompositeAnalysis/VertexCompositeProducer/test/crab/crab.log
DEBUG 2025-07-11 18:49:58.741 UTC: 	 CRAB Client version: v3.250522
DEBUG 2025-07-11 18:49:58.741 UTC: 	 Running on: Linux cms-fe00.rcac.purdue.edu 4.18.0-513.18.1.el8_9.x86_64 #1 SMP Wed Feb 21 21:34:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-07-11 18:49:58.742 UTC: 	 Not using Singularity
DEBUG 2025-07-11 18:49:58.742 UTC: 	 Operating System: Rocky Linux 8.9 (Green Obsidian)
DEBUG 2025-07-11 18:49:58.742 UTC: 	 Executing command: 'kill'
DEBUG 2025-07-11 18:49:58.742 UTC: 	 Found CRAB cache file /home/awesole/.crab3
ERROR 2025-07-11 18:49:58.744 UTC: 	 Cannot find .requestcache file in CRAB project directory /home/awesole/VertexCP_2/CMSSW_13_2_11/src/VertexCompositeAnalysis/VertexCompositeProducer/test/crab/test_1_file/crab_test_1_file
ERROR 2025-07-11 18:49:58.745 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 695, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 537, in loadLocalCache
    raise ex
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 531, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/ClientUtilities.py", line 445, in loadCache
    raise CachefileNotFoundException(msg)
CRABClient.ClientExceptions.CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /home/awesole/VertexCP_2/CMSSW_13_2_11/src/VertexCompositeAnalysis/VertexCompositeProducer/test/crab/test_1_file/crab_test_1_file
INFO 2025-07-11 18:49:58.748 UTC: 	 Log file is /home/awesole/VertexCP_2/CMSSW_13_2_11/src/VertexCompositeAnalysis/VertexCompositeProducer/test/crab/crab.log
DEBUG 2025-07-11 18:50:16.352 UTC: 	 CRAB Client version: v3.250522
DEBUG 2025-07-11 18:50:16.353 UTC: 	 Running on: Linux cms-fe00.rcac.purdue.edu 4.18.0-513.18.1.el8_9.x86_64 #1 SMP Wed Feb 21 21:34:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-07-11 18:50:16.353 UTC: 	 Not using Singularity
DEBUG 2025-07-11 18:50:16.353 UTC: 	 Operating System: Rocky Linux 8.9 (Green Obsidian)
DEBUG 2025-07-11 18:50:16.353 UTC: 	 Executing command: 'status'
DEBUG 2025-07-11 18:50:16.354 UTC: 	 Found CRAB cache file /home/awesole/.crab3
ERROR 2025-07-11 18:50:16.355 UTC: 	 Cannot find .requestcache file in CRAB project directory /home/awesole/VertexCP_2/CMSSW_13_2_11/src/VertexCompositeAnalysis/VertexCompositeProducer/test/crab/test_1_file/crab_test_1_file
ERROR 2025-07-11 18:50:16.355 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/status.py", line 49, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 695, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 537, in loadLocalCache
    raise ex
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 531, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/ClientUtilities.py", line 445, in loadCache
    raise CachefileNotFoundException(msg)
CRABClient.ClientExceptions.CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /home/awesole/VertexCP_2/CMSSW_13_2_11/src/VertexCompositeAnalysis/VertexCompositeProducer/test/crab/test_1_file/crab_test_1_file
INFO 2025-07-11 18:50:16.360 UTC: 	 Log file is /home/awesole/VertexCP_2/CMSSW_13_2_11/src/VertexCompositeAnalysis/VertexCompositeProducer/test/crab/crab.log
DEBUG 2025-07-11 18:51:21.113 UTC: 	 CRAB Client version: v3.250522
DEBUG 2025-07-11 18:51:21.114 UTC: 	 Running on: Linux cms-fe00.rcac.purdue.edu 4.18.0-513.18.1.el8_9.x86_64 #1 SMP Wed Feb 21 21:34:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-07-11 18:51:21.114 UTC: 	 Not using Singularity
DEBUG 2025-07-11 18:51:21.114 UTC: 	 Operating System: Rocky Linux 8.9 (Green Obsidian)
DEBUG 2025-07-11 18:51:21.114 UTC: 	 Executing command: 'submit'
DEBUG 2025-07-11 18:51:21.115 UTC: 	 Found CRAB cache file /home/awesole/.crab3
INFO 2025-07-11 18:51:21.116 UTC: 	 Will use CRAB configuration file D0_data_lumiTest.py
DEBUG 2025-07-11 18:51:21.117 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-07-11 18:51:21.184 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-07-11 18:51:21.185 UTC: 	 Working area '/home/awesole/VertexCP_2/CMSSW_13_2_11/src/VertexCompositeAnalysis/VertexCompositeProducer/test/crab/data_lumi_test/crab_data_lumi_test' already exists 
Please change the requestName in the config file
ERROR 2025-07-11 18:51:21.185 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250522.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/home/awesole/VertexCP_2/CMSSW_13_2_11/src/VertexCompositeAnalysis/VertexCompositeProducer/test/crab/data_lumi_test/crab_data_lumi_test' already exists 
Please change the requestName in the config file
INFO 2025-07-11 18:51:21.190 UTC: 	 Log file is /home/awesole/VertexCP_2/CMSSW_13_2_11/src/VertexCompositeAnalysis/VertexCompositeProducer/test/crab/crab.log
